### ISSUE TITLE
Weapon disappearing after moving for a while

### ISSUE THREAD

**Issue by chris-gong** [chris-gong/fortnite-clone-ue4#8]
Not sure of the cause at the moment, but I have noticed that if you are running for a while and do not anything besides just holding the weapon, then it disappears graphically. However, the weapon can still be used. For example, if you were holding a gun, you can still shoot with it.

**Comment by chris-gong** [comment]
Actually, although the shooting animation happens, `CurrentWeapon` is actually `nullptr` when the weapon "disappears".

**Comment by 0xsmft** [comment]
Issue Fixed

**Comment by 0xsmft** [comment]
To me, the issue was the scale so this is what I did to counter it 

- Imported a new shotgun (same one but proper size) 

-  Made it so that it uses complex collision 

-  Then made it so that it set's the pos and rot depending on the socket 

- New stuff that I added 

1.  New FName for the "WeaponAttachSocketName" (WeaponAttachSocketName is just the rifle but then its gets set to the shotgun)

2. the same but in the WeaponActor called AttachSocketName

**Comment by 0xsmft** [comment]
Also fixed weapon spawning by using ESpawnActorCollisionHandlingMethod::AlwaysSpawn
